# Generated by Django 5.1.1 on 2024-10-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('idCategoria', models.UUIDField(help_text='ID único para tipo de producto', primary_key=True, serialize=False)),
                ('nomCategoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='metodos_pago',
            fields=[
                ('id_metodo', models.UUIDField(help_text='ID único para tipo de metodo', primary_key=True, serialize=False)),
                ('tipo_metodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pedido_detalles',
            fields=[
                ('idDetalle', models.UUIDField(help_text='ID único para tipo de detalle del pedido', primary_key=True, serialize=False)),
                ('total_productos', models.IntegerField()),
                ('precio_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('idUsuario', models.UUIDField(help_text='ID único para tipo de usuario', primary_key=True, serialize=False)),
                ('nomUsuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(null=True)),
                ('fecha_nac', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.IntegerField()),
                ('tipo_usuario', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_carrito', models.UUIDField(help_text='ID único para tipo de detalle del carrito', primary_key=True, serialize=False)),
                ('total_productos', models.IntegerField()),
                ('precio_total', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.pedido_detalles')),
            ],
        ),
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('idPedido', models.UUIDField(help_text='ID único para tipo de pedido', primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(null=True)),
                ('total_productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.carrito')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id_pago', models.UUIDField(help_text='ID único para tipo de pago', primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.IntegerField()),
                ('estado_pago', models.CharField(max_length=50)),
                ('idmetodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.metodos_pago')),
                ('idPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('idProducto', models.UUIDField(help_text='ID único para tipo de producto', primary_key=True, serialize=False)),
                ('nomProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('precioProducto', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.categorias')),
            ],
        ),
    ]
