# Generated by Django 5.1.2 on 2024-10-28 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_usuarios_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.UUIDField(default=uuid.uuid4, help_text='ID único para tipo de producto', primary_key=True, serialize=False)),
                ('nomCategoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.UUIDField(default=uuid.uuid4, help_text='ID único para tipo de producto', primary_key=True, serialize=False)),
                ('nomProducto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='categorias',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
