# Generated by Django 5.1.2 on 2024-10-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_categoria_remove_productos_categoria_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.DecimalField(decimal_places=2, help_text='Precio en pesos colombianos (COP)', max_digits=10),
        ),
    ]
